extends:
  - 'eslint:recommended'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'

parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
root: true

env:
  node: true

parserOptions:
  ecmaVersion: latest

rules:
  import/order:
    - 'error'
    - groups:
        - 'builtin'
        - 'external'
        - 'internal'
        - 'parent'
        - 'sibling'
        - 'index'
        - 'object'
        - 'type'

  import/newline-after-import:
    - error

settings:
  import/resolver:
    typescript: {}
